### ISSUE TITLE
How should I slove these problem

### ISSUE THREAD

**Issue by lceLCE** [netrumbtw/jar2dll#1]
## The first problem is:
![image](https://user-images.githubusercontent.com/98255117/200799825-4abcd9e2-66a1-4379-82fa-e91a9f416fe1.png)

## The second is:

![image](https://user-images.githubusercontent.com/98255117/200800030-fa04152c-02c9-4216-a3b9-519f68b307fc.png)

My jar is a forge mod for minecraft 1.8.9

**Comment by netrumbtw** [comment]
Can you provide problem JAR?

**Comment by myaww1337** [comment]
Enable "Save C++ Source" and send me output file (See the console log to get source file location)

**Comment by myaww1337** [comment]
I guess your problem was fixed now.
Check out [latest release](https://github.com/netrumbtw/jar2dll/releases/tag/stable-091122) and try to compile.
Please tell me are this bug was fixed?

**Comment by lceLCE** [comment]
The problem has been completely solved!
Thank you very much!
